name = input()
price = int(input())
weight = int(input())
payment = int(input())
print("================Чек================")
print("Товар:" + f"{name:>29}")
print("Цена:" + f"{f"{weight}кг * {price}руб/кг":>30}")
print("Итого:" + f"{f"{weight * price}руб":>29}")
print("Внесено:" + f"{f"{payment}руб":>27}")
print("Сдача:" + f"{f"{payment - weight * price}руб":>29}")
print("===================================")